import React from "react";

interface JsonLdProps {
  type: "organization" | "faq" | "breadcrumb";
  faqItems?: { question: string; answer: string }[];
  breadcrumbItems?: { name: string; item: string }[];
}

export default function JsonLd({ type, faqItems, breadcrumbItems }: JsonLdProps) {
  let data: any = null;

  if (type === "organization") {
    data = {
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "FinancialService",
          "@id": "https://app.irion.finance/#organization",
          "name": "IRION Finance",
          "url": "https://app.irion.finance",
          "logo": "https://app.irion.finance/irion-logo.png",
          "image": "https://app.irion.finance/irion-logo.png",
          "description": "Private consumer credit on Canton — BNPL, lending, and a credit line in a private Daml contract.",
          "tagline": "Buy Now, Pay Never.",
          "feesAndCommissionsSpecification": "Auto-repaid from on-chain yield generated by collateral assets.",
          "sameAs": [
            "https://x.com/IrionFinance"
          ]
        },
        {
          "@type": "WebSite",
          "@id": "https://app.irion.finance/#website",
          "url": "https://app.irion.finance",
          "name": "IRION Finance",
          "description": "Private consumer credit on Canton: BNPL, lend/borrow, and a private credit line.",
          "publisher": {
            "@id": "https://app.irion.finance/#organization"
          }
        }
      ]
    };
  } else if (type === "faq") {
    const items = faqItems || [
      {
        question: "What is Buy Now, Pay Never?",
        answer: "Buy Now, Pay Never (BNPL) allows users to purchase items on credit by locking USDC collateral. The collateral is supplied to the Irion lending pool on Canton to generate yield, and the earned yield pays off the outstanding credit over time."
      },
      {
        question: "How is my credit kept private on Canton?",
        answer: "Privacy is built into Canton. A Daml contract is only visible to its signatory and observer parties, so your credit profile and loans are seen only by you and the operator. The synchronizer that orders transactions sees only encrypted commitments — never your data. This replaces zero-knowledge proofs with privacy-by-construction."
      },
      {
        question: "Is my financial data private?",
        answer: "Yes. Your balances, credit line, and loans live in Daml contracts whose only informees are you and the operator. No other participant — not even other IRION users — can inspect them."
      },
      {
        question: "What is IRION Finance built on?",
        answer: "IRION Finance is built on the Canton Network using Daml smart contracts, leveraging sub-transaction privacy and atomic, multi-party settlement to handle collateral management, lending pools, and BNPL checkouts."
      }
    ];
    data = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": items.map((item) => ({
        "@type": "Question",
        "name": item.question,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": item.answer
        }
      }))
    };
  } else if (type === "breadcrumb") {
    data = {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": (breadcrumbItems || []).map((item, index) => ({
        "@type": "ListItem",
        "position": index + 1,
        "name": item.name,
        "item": item.item
      }))
    };
  }

  if (!data) return null;

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
